### ISSUE TITLE
目次

### ISSUE THREAD

**Issue by pe227merrypink** [nyanpass-jp/narou_tool#10]
目次に章管理で設定された章名が表示されてない。

章が変わるごとに話数が一話に戻る場合があるし、さすがに無いと不便

章管理で章名を入れられる関係で、話名に章数を入れてない作者が大半なので…

**Comment by pe227merrypink** [comment]
話名に改行が入ってた場合、Epubにもそれが反映されてしまう。

`<h1>話名<br>`
`【後書き】</h1>`

といった感じになる。

なろう的には話名に改行コードが入ってても改行表示されないがEpubだと改行されてしまう。

**Comment by nyanpass-jp** [comment]
目次の章対応、タイトルのタグ除去行いました。

ご報告ありがとうございました。
