### ISSUE TITLE
横書き設定なのに右綴じになる

### ISSUE THREAD

**Issue by b2ox** [nyanpass-jp/narou_tool#13]
"横書きレイアウトでダウンロードする"にチェックを入れて処理すると、一応横書きのが出来ますが、綴じ方向が縦書きレイアウトのままです。
具体的にはcontent.opfの目次記述でpage-progression-directionが"rtl"のままになっているので、これを"ltr"に変更する必要があります。

あと、各コンテンツ(.xhtml)のhtmlタグにclass="vrtl"があるのですが、これも縦書き用の設定だと思うので、横書き用に設定を変える必要があると思います。

**Comment by nyanpass-jp** [comment]
対応しました。
ご報告ありがとうございました。
