### ISSUE TITLE
カクヨムの傍点

### ISSUE THREAD

**Issue by darkgray1981** [nyanpass-jp/narou_tool#21]
カクヨムの傍点がバグります。

たとえば
https://kakuyomu.jp/works/1177354054882739112/episodes/1177354054882769095
の傍点は本来こうですが:
![kakuyomu](https://user-images.githubusercontent.com/2127005/54480653-269b0d00-482b-11e9-8fed-9b69ff1c2723.png)

キンドルではこうなっちゃうんです:
![kindle](https://user-images.githubusercontent.com/2127005/54480666-74b01080-482b-11e9-9df1-3f378b25b91a.jpg)

**Comment by nyanpass-jp** [comment]
遅くなりましたがこちら対応しました。
