### ISSUE TITLE
Mobi化での行間

### ISSUE THREAD

**Issue by sinku2009** [nyanpass-jp/narou_tool#23]
Mobi形式に変化した時に行間が異常に広いです。
n8769bz、n1474fhの作品で確認しました。
リーダーはWindows版KindleとKindlePaperwhiteです。

こんなかんじ
[https://imgur.com/VWNdINo](https://imgur.com/VWNdINo)

**Comment by nyanpass-jp** [comment]
こちら対応しました。
ご報告ありがとうございました。
