### ISSUE TITLE
Epub Validation Error

### ISSUE THREAD

**Issue by nigyo190creampink** [nyanpass-jp/narou_tool#4]
作成されるEpubにエラーが有る。

EPUBバリデータに重大レベルのエラー2つ
メタ情報に注意レベルのエラー2つ
が有る。

重大エラーの1つ目は、OEBPS/navdoc.xhtmlの拡張子はxhtmlになってないといけないのにhtmlになってる事
重大エラーの2つ目は、http-equiv の値が正規表現にマッチしてない事
尚、正規値は↓
([Dd][Ee][Ff][Aa][Uu][Ll][Tt]\-[Ss][Tt][Yy][Ll][Ee])|([Rr][Ee][Ff][Rr][Ee][Ss][Hh])|([Cc][Oo][Nn][Tt][Ee][Nn][Tt]\-[Tt][Yy][Pp][Ee])

注意エラーの1つ目は、メタ情報に電書協バージョンタグが無いこと
電書協仕様準拠の場合、バージョンタグが必要。

日本のソフトの場合、電書協仕様を部分準拠する形で作成されてるから、電書協仕様準拠の時に必要なタグを追加する必要がある。

注意エラーの2つ目は、カバー画像が無い事
なろうの場合は関係ないけど、Epubは本来商用利用だからメタ情報にカバー画像が無いとエラー扱いになる。

**Comment by gyadorirurube** [comment]
挿絵無し時はEpubにエラーは出てないけど、挿絵があると重大エラーが出る

EPUB version 3.0.1 のルールを使って検証

重大エラー1つ目

挿絵の属性にborderは使えない。

使えるのは、 "about", "accesskey", "alt", "aria-activedescendant", "aria-atomic", "aria-autocomplete", "aria-busy", "aria-checked", "aria-controls", "aria-describedat", "aria-describedby", "aria-disabled", "aria-dropeffect", "aria-expanded", "aria-flowto", "aria-grabbed", "aria-haspopup", "aria-hidden", "aria-invalid", "aria-label", "aria-labelledby", "aria-level", "aria-live", "aria-multiline", "aria-multiselectable", "aria-orientation", "aria-owns", "aria-posinset", "aria-pressed", "aria-readonly", "aria-relevant", "aria-required", "aria-selected", "aria-setsize", "aria-sort", "aria-valuemax", "aria-valuemin", "aria-valuenow", "aria-valuetext", "class", "content", "contenteditable", "contextmenu", "datatype", "dir", "draggable", "dropzone", "epub:type", "height", "hidden", "id", "inlist", "ismap", "itemid", "itemprop", "itemref", "itemscope", "itemtype", "lang", "ns:alphabet", "ns:ph", "onabort", "onblur", "oncanplay", "oncanplaythrough", "onchange", "onclick", "oncontextmenu", "ondblclick", "ondrag", "ondragend", "ondragenter", "ondragleave", "ondragover", "ondragstart", "ondrop", "ondurationchange", "onemptied", "onended", "onerror", "onfocus", "oninput", "oninvalid", "onkeydown", "onkeypress", "onkeyup", "onload", "onloadeddata", "onloadedmetadata", "onloadstart", "onmousedown", "onmousemove", "onmouseout", "onmouseover", "onmouseup", "onmousewheel", "onpause", "onplay", "onplaying", "onprogress", "onratechange", "onreadystatechange", "onreset", "onscroll", "onseeked", "onseeking", "onselect", "onshow", "onstalled", "onsubmit", "onsuspend", "ontimeupdate", "onvolumechange", "onwaiting", "prefix", "property", "rel", "resource", "rev", "role", "spellcheck", "style", "tabindex", "title", "typeof", "usemap", "vocab", "width", "xml:base", "xml:lang"


重大エラー二つ目

挿絵の画像データがEPUB内に存在してるが、OPFマニフェストで宣言されてない

**Comment by nyanpass-jp** [comment]
画像のopfへの追加以外は対応しました。

**Comment by gyadorirurube** [comment]
画像のopfへの追加は簡単ですよ。

content.opfに該当項目追加すればいいだけなので…

ファイルの場所が、

content.opf Sample.epub\OEBPS

chapter_a_*.xhtmlなどの本文ファイル  Sample.epub\OEBPS\Text

画像ファイル(JPEG) Sample.epub\OEBPS\Images

の場合

`<item id="chapter_a_53" href="Text/chapter_a_53.xhtml" media-type="application/xhtml+xml"/>`
`<item id="画像ファイル名.jpeg" href="Images/画像ファイル名.jpeg" media-type="image/jpeg(ファイルのMiME-Type)"/>`
`</manifest>`
`<spine page-progression-direction="rtl" toc="tocncx">`
`<itemref idref="title_page"/>`
`<itemref idref="chapter_h_1"/>`

画像が複数有る場合は、

`<item id="画像ファイル名.jpeg" href="Images/画像ファイル名.jpeg" media-type="image/jpeg(ファイルのMiME-Type)"/>`

を画像分増やせばいい。

**Comment by gyadorirurube** [comment]
後、挿絵の有無を選べるようにした方がいい。

標準だと挿絵が表示されるが、挿絵非表示機能は、なろう公式にも有るんだし…

ファイル名も今はNcodeだけど作品名にするオプションも要る。

**Comment by nyanpass-jp** [comment]
manifestへの画像の追加と、挿絵の有無について対応しました。
