### ISSUE TITLE
改行コード異常

### ISSUE THREAD

**Issue by gugu796neko2net** [nyanpass-jp/narou_tool#7]
改行コードＬＦが、\nという形でEpubのコードに入ってしまってる。

タグとして認識されてるから、通常表示だと空白表示で判らないが、コード表示だと改行コードＬＦが\nという特殊文字として表示されてるからシステム的には問題がある。

特殊文字扱いだから、通常の改行と違って余計な容量食うし、\はJisだと¥表示される

**Comment by nyanpass-jp** [comment]
試作乙拾九型で復旧。
改行禁則校正を行った場合で該当の現象を確認しました。
