### ISSUE TITLE
CSS Validation Error

### ISSUE THREAD

**Issue by myabigu895macr2com** [nyanpass-jp/narou_tool#9]
作成されたEpubのCSSを検証したら、CSSにエラーが出た

エラーは↓

org.w3c.css.properties.css3.Css3Style cannot be cast to org.w3c.css.properties.svg.SVGBasicStyle

問題の有る部分は、↓

*  { 

line-height : 125%; 
} 

検証には、W3C CSS 検証サービスを使用

http://jigsaw.w3.org/css-validator/

**Comment by nyanpass-jp** [comment]
SVG用のCSSではないので、問題ないエラーです。
縦書き設定を入れると出るものですね。
